version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 9910:3306
    environment:
      - MYSQL_DATABASE=sorm
      - MYSQL_USER=sorm
      - MYSQL_PASSWORD=sorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  postgres:
    image: 'postgres:latest'
    ports:
      - 9920:5432
    environment:
      - POSTGRES_USER=sorm
      - POSTGRES_DB=sorm
      - POSTGRES_PASSWORD=sorm
  mssql:
    image: 'mcmoe/mssqldocker:latest'
    ports:
      - 9930:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=LoremIpsum86
      - MSSQL_DB=xorm
      - MSSQL_USER=sorm
      - MSSQL_PASSWORD=LoremIpsum86